### ISSUE TITLE
Solution Requires C# 7.1

### ISSUE THREAD

**Issue by ahoefling** [jamesmontemagno/Hanselman.Forms#107]
> Built with C# 6 features, you must be running VS 2015 or Xamarin Studio to compile.

The README file cites the application is built using C# 6, but when I tried building it I ran into build errors in the Android project that stated the android project required C# 7.1. This was easily fixed by updating the C# version in the project settings.

**Comment by jamesmontemagno** [comment]
I think it works when you build in 2019, which I have moved over to and it defaults to 7.3 :) We should probably set it though.

**Comment by jamesmontemagno** [comment]
Fixed
