### ISSUE TITLE
Windows Phone 8.1 Project?

### ISSUE THREAD

**Issue by Michael-DST** [jamesmontemagno/Hanselman.Forms#11]
Hello... LOVED the introduction @ dotnetconf!  That was a really enjoyable video.

Secondly... I'm a little confused around the Windows Phone integration, and was hoping to get some clarification.  Windows Store (8.1) support was announced on Thursday, and from my understanding 8.1 means Universal Apps.  Does that mean this project's Phone sample can update to 8.1 as well?

Thank you in advance for any clarification.

**Comment by Michael-DST** [comment]
After looking through the code, there does appear to be a Xamarin.Forms.Platform.WinRT.Phone.dll provided in the Xamarin.Forms.Windows package.  So perhaps a Windows Phone 8.1 Project is on the way. :)

**Comment by jamesmontemagno** [comment]
Yes this is all you have to do. I will be adding it soon, you can just copy in the code from the Store project at this point. There are plenty of docs that I link to which show you how to set this up.

**Comment by Michael-DST** [comment]
Super awesome.  I can't speak enough about how awesome this all is.  It's like Silverlight all over again, except so much more real and viable.  Thank you for putting this all together and for that great video (once again!).  Really exciting stuff.  Looking forward to //build and beyond. :smile:
