### ISSUE TITLE
Irregular vertical space between the Play Icon and other podcast icons

### ISSUE THREAD

**Issue by manutdkid77** [jamesmontemagno/Hanselman.Forms#120]
On iOS devices, there is lot of irregular vertical space between the Play icon and the Podcast icons such as Download, Up Next.

This issue occurs when the `Visual` property of the ActivityIndicator is set to `Material`.

The fix is to set the WidthRequest of the ActivityIndicator to 48, which is the default dimension as specified in [google material docs](https://material.io/design/components/progress-indicators.html#specs)

Should we file an issue in the XamarinForms repo or can I submit a PR with the WidthRequest set to 48?

Screenshot:
![screenshot 67](https://user-images.githubusercontent.com/14297705/58262400-d8106e80-7d97-11e9-8ccf-6535e7b0cf91.png)

**Comment by manutdkid77** [comment]
This issue also occurs on PodcastDetailsPage for the ActivityIndicator.

![iphonex_activityindicator_bug](https://user-images.githubusercontent.com/14297705/58717662-5c42a180-83e9-11e9-951c-e80f6f037c1a.gif)

**Comment by jamesmontemagno** [comment]
This should all be fixe dup now.
