### ISSUE TITLE
Play button in PodCastPlayback clips

### ISSUE THREAD

**Issue by haavamoa** [jamesmontemagno/Hanselman.Forms#137]
Hi @jamesmontemagno , I was creating a pull request for your repository and found out that the play button the podcast playback view clips to (about) half.

See image below:
![image](https://user-images.githubusercontent.com/2527084/63076780-a04c3980-bf36-11e9-8071-ad4bb7950440.png)

This is only tested on an `Android` simulator and a Huawei p30 device.

**Comment by haavamoa** [comment]
Did you resolve this yesterday @jamesmontemagno?

**Comment by jamesmontemagno** [comment]
Yup all good now :) closing out :)
