### ISSUE TITLE
When I press "Stop" and then "Play" it is not playing anything

### ISSUE THREAD

**Issue by tkowalczyk** [jamesmontemagno/Hanselman.Forms#17]

**Comment by tkowalczyk** [comment]
@jamesmontemagno any ideas about how to fix this issue?
thx

**Comment by jamesmontemagno** [comment]
The code for playback is really just "demo"  I didn't test every scenario. You ideally would have background services with proper implementation for streaming music. I haven't looked into this issue.

**Comment by tkowalczyk** [comment]
@jamesmontemagno thank you for your response, could you tell me more about these background services or point me where to read about those? I would like to have similar solution which will be ready for production. Thanks for your time.

**Comment by jamesmontemagno** [comment]
For android look here: https://github.com/jamesmontemagno/AndroidStreamingAudio

iOS: http://developer.xamarin.com/guides/ios/application_fundamentals/backgrounding/part_3_ios_backgrounding_techniques/
