### ISSUE TITLE
Memory leak in Blogs

### ISSUE THREAD

**Issue by hulluP** [jamesmontemagno/Hanselman.Forms#174]
Hi James

Thanks for the great example App. I found a memory leak in your Blogs section though. Could you show on the live stream how you would hunt down root cause. As far as I saw this was in the CollectionView on iOS. Would be great for the community to see how you hunt this down in detail.

way to reproduce is

1. start profiling with iOS simulator
2. open the blogs screen
3. Refresh the blogs by pulling down.
4. monitor the BlogFeed model. 

it should not go up but it does with each refresh.
![Screenshot 2020-03-17 at 08 49 04](https://user-images.githubusercontent.com/46395952/76834400-6aa16300-682d-11ea-8d3d-60198977ec61.png)

Thanks HP

**Comment by hartez** [comment]
@hulluP I notice in your Profiler screenshot that the "Only Live Objects" checkbox is unchecked - IIRC, this means that it's also showing objects which were allocated and have since been collected.

If you check that box and profile the application, do you see the same behavior? Does the count of `BlogFeedItem` instances continue to go up forever?

**Comment by hulluP** [comment]
@hartez 
Unfortunately the frame is covering the names of the columns the live Object count for the `BlogFeedItem` is 81 and the total count is 171. You are right the total count should go up that is expected. But the live count should go down again after each garbage collection. It will never go to zero as some blogs are always show.

**Comment by jfversluis** [comment]
I do have a potential bug for it logged here as well https://github.com/xamarin/Xamarin.Forms/issues/9787

**Comment by jamesmontemagno** [comment]
Will close as this is in core, not the app. :)
