### ISSUE TITLE
How to put animation icon

### ISSUE THREAD

**Issue by gabrielSwp** [jamesmontemagno/Hanselman.Forms#20]

**Comment by gabrielSwp** [comment]
@jamesmontemagno I have a doubt, when I click the icon to display the MENU, the icon does not have that animation, as it could put the animation on the icon?

**Comment by jamesmontemagno** [comment]
I am not exactly sure what you are talking about here to be honest.

**Comment by gabrielSwp** [comment]
in my example is when to display the menu, displaying it differently, I wanted to know why and also realized that the project android does not contain the file "slideout.png"

My samples
![mysamples](https://cloud.githubusercontent.com/assets/13755005/11284327/e4c0c99c-8ee7-11e5-8249-00028fe12b75.gif)

Samples Hanselman.Forms
![sampleforms](https://cloud.githubusercontent.com/assets/13755005/11284540/170bbe2e-8ee9-11e5-9fd7-fbc10b778747.gif)

**Comment by jamesmontemagno** [comment]
Thanks for the context. You are not using the new Material Design AppCompat version of Xamarin.Forms: read through: https://blog.xamarin.com/material-design-for-your-xamarin-forms-android-apps/
