### ISSUE TITLE
changing the colors in the style

### ISSUE THREAD

**Issue by angelSwp** [jamesmontemagno/Hanselman.Forms#24]
@jamesmontemagno  I'm changing the colors in the style file, but does not change the blue color navigationBar

**Comment by jamesmontemagno** [comment]
Depends on which OS, you would need to update:
https://github.com/jamesmontemagno/Hanselman.Forms/blob/master/Hanselman.Portable/Controls/HanselmanNavigationPage.cs#L21-L22
https://github.com/jamesmontemagno/Hanselman.Forms/blob/master/Hanselman.iOS/AppDelegate.cs#L30-L36
and
https://github.com/jamesmontemagno/Hanselman.Forms/blob/master/Hanselman.Android/Resources/values/Colors.xml#L3

**Comment by angelSwp** [comment]
@jamesmontemagno  How do I change the color of the selected item in my listview?

**Comment by jamesmontemagno** [comment]
You should ask questions over at http://forums.xamarin.com as I do not provide support for general development.
