### ISSUE TITLE
Can't find slideout.png in Android project

### ISSUE THREAD

**Issue by omscarr** [jamesmontemagno/Hanselman.Forms#25]
Hi @jamesmontemagno,
Great demonstration project, but I am confused at how the "hamburger" menu logo on android works.
In MenuPage you specify the Icon in the BindingContext as "slideout.png".
The iOS, WinPhone, and WinStore projects all have the file slidout.png in them, but I can't find it anywhere in the Android project.

Why doesn't this throw an exception that the resource could not be found?

**Comment by jamesmontemagno** [comment]
I have upgrade the Android project to the new AppCompat version which has it all included as it is a standard control from Google: https://blog.xamarin.com/material-design-for-your-xamarin-forms-android-apps/
