### ISSUE TITLE
Set the MasterDetailPage "RootPage" as a NavigationPage

### ISSUE THREAD

**Issue by Goldstrike** [jamesmontemagno/Hanselman.Forms#27]
@jamesmontemagno  
Hello,

I work on a **Xamarin.Forms** project with **MVVMLight**, where the main page must been a **MasterDetailPage**.
I have read your article about the **Material Design** and I have tried your sample "**Hanselman.Forms**", as I want to implement something like this in my project.
I would also use a **navigation "ViewModel first"**. For this, I use the **Navegar **package, which allows me to manage this easily: 
[https://github.com/mplessis/navegar](url)
[https://www.nuget.org/packages/Navegar/](url)

But I currently meet a **problem if the OS version of Android >= 5.1**: I have a "gap" on my screen:
[http://img15.hostingpics.net/pics/963309FormsAppCompatActivityAnd51WithNavegar.png](url)
There is **no problem for older versions (<5.1)**:
[http://img15.hostingpics.net/pics/528135FormsAppCompatActivityAnd44WithNavegar.png
](url)

Would you have an iadea about the encountered problem?
Is there another way to adapt your code to ViewModel navigation?

Regards,

**Comment by jamesmontemagno** [comment]
I would ask over on the forums.
