### ISSUE TITLE
Needs update for new Xamarin Forms

### ISSUE THREAD

**Issue by AroglDarthu** [jamesmontemagno/Hanselman.Forms#28]
The Portable project does not build in Visual Studio 2015 Update 2.

It has missing references for Xamarin.Forms.Core.Design and Xamarin.Forms.Xaml.Design. Also, it complains: Build action 'EmbeddedResource' is not supported by one or more of the project's targets.

**Comment by jamesmontemagno** [comment]
Updated

**Comment by slombardo** [comment]
It seems this issue is still a problem.

To reproduce, clone the repo, build & run.  Fixed in #36.
