### ISSUE TITLE
MIssing slideout.png in Android project

### ISSUE THREAD

**Issue by RobDaPraia** [jamesmontemagno/Hanselman.Forms#30]
When running the Android project you will get an error __Resource not found__.

Added a slideout.png to folder\Hanselman.Forms\Hanselman.Android\Resources\drawable to resolve the isssue

**Comment by jamesmontemagno** [comment]
I have added one, but I did not see an exception at all running it on my machine. What emulator or device where you using?

**Comment by RobDaPraia** [comment]
I used the Android Emulator in Visual Studio. If for example I remove the slideout.png from the project I get again the error, see screenshots

![hanselman2](https://cloud.githubusercontent.com/assets/3207395/16626631/206562d8-43aa-11e6-920e-9b1ec563d181.jpg)

![hanselman1](https://cloud.githubusercontent.com/assets/3207395/16626644/28e2063c-43aa-11e6-9716-3a330f5e6995.jpg)

![hanselman3](https://cloud.githubusercontent.com/assets/3207395/16626650/2d171d3c-43aa-11e6-8ac5-b6cda149f51f.jpg)

**Comment by jamesmontemagno** [comment]
If you pull the latest it is in there. Thanks for the screenshots.

**Comment by RobDaPraia** [comment]
Thanks for the update

This example helped me a lot to create a first Xamarin app with MVVM, menu page and master detail
