### ISSUE TITLE
How can I add icons to the toolbar?

### ISSUE THREAD

**Issue by Emasoft** [jamesmontemagno/Hanselman.Forms#33]
How can I add icons to the toolbar?
Like in the following apps:

![espn-material-design](https://cloud.githubusercontent.com/assets/713559/18610223/b4b9b90c-7d16-11e6-831a-36924ae479b4.png)

![material design bar slanted](https://cloud.githubusercontent.com/assets/713559/18610228/cb90f992-7d16-11e6-97c3-36d28ddc490c.png)

**Comment by jamesmontemagno** [comment]
I would ask in the forums, I do not answer support type questions here sorry. Google will bring you to: http://codeworks.it/blog/?p=232

**Comment by Emasoft** [comment]
Ok @jamesmontemagno , but I just want to point up that the is one important missing piece in your collection of excellent examples for Xamarin.Forms: a good toolbar component, with badges notifications, tabs, and custom fonts. Please consider doing it, it would be very helpful.
