### ISSUE TITLE
Wrong behavior of hamburger menu on iOS version

### ISSUE THREAD

**Issue by karolzak** [jamesmontemagno/Hanselman.Forms#35]
Navigation with hamburger menu works ok on UWP and Android (menu works as an flyout which is rendered on top of content of the app) but on iOS it kinda slides the whole content out of the screen.
It's not a big issue but I wonder if there's any easy fix for that and why exactly is it behaving like that.

Screenshots from Android and iOS attached
Android (notice how menu renders on top of content):
![adnroidss](https://cloud.githubusercontent.com/assets/9843623/21424648/82b87992-c844-11e6-88fb-93ea9e9b6155.png)

iOS (notice how menu pushes the content out of the screen):
![iosss](https://cloud.githubusercontent.com/assets/9843623/21424649/82b89602-c844-11e6-821f-0aeeed167b5f.png)

**Comment by jamesmontemagno** [comment]
This is how Xamarin.Forms works and is the expected result
