### ISSUE TITLE
PropertyChanged not working

### ISSUE THREAD

**Issue by JanWidm** [jamesmontemagno/Hanselman.Forms#41]
Hello, I used your project (the navigation) as a template for me and changed a few things up. Now I have the problem that ImplementPropertyChanged (Nuget: PropertyChanged.Fody) is not working correctly. Is there a known problem with this Nuget and the MasterDetailPage?

Regards,
Jan

**Comment by jamesmontemagno** [comment]
I have never used Fody sorry.

**Comment by JanWidm** [comment]
Yeah, by mistake I deleted : INotifyPropertyChanged. Adding it again and delete Fody was the solution for my problem. Great Project and Template. @jamesmontemagno
