### ISSUE TITLE
Cannot build 

### ISSUE THREAD

**Issue by ETHwsch** [jamesmontemagno/Hanselman.Forms#44]
I tried to build the app in VS2017 and Xamarin Studio (latest version) but it did not work.
In VS2017 the nuget packages are not restored and all references had  the little yellow Warning symbol. I tried all suggestions described here https://forums.xamarin.com/discussion/56559/vs-2015-errors-on-sample-projects

In Xamarin Studio I am getting "This project references NuGet package(s) that are missing on this computer"

If I try to patch the .csproj file in, any suggested way, I have all sort of other issues.

Any idea?

**Comment by jamesmontemagno** [comment]
Did you restore the nugets?

**Comment by ETHwsch** [comment]
Ohh - I accidently downloaded the App from here https://github.com/AweSamNet/Hanselman.Forms-Starter-Project-Template-for-VS-2015. Found it accidently via googling.
Loading the App from the correct side works perfectly.

Sorry and thanks.
