### ISSUE TITLE
Can we get some tutorial on how to implement ExoPlayer in Xamarin forms? 

### ISSUE THREAD

**Issue by YLPeng** [jamesmontemagno/Hanselman.Forms#45]

**Comment by YLPeng** [comment]
Does it require special initiation in MainActivity other than Android.VideoViewRenderer.Init();?

**Comment by jamesmontemagno** [comment]
https://blog.xamarin.com/play-audio-and-video-with-the-mediamanager-plugin-for-xamarin/
