### ISSUE TITLE
Menu hamburger missing in UWP

### ISSUE THREAD

**Issue by slombardo** [jamesmontemagno/Hanselman.Forms#46]
So this has been happening for a while, and it seems reverting xamarin.forms to an older version seems to fix it.

When using the latest version, you can see the hamburger does not appear:
![image](https://user-images.githubusercontent.com/1529389/27213158-03662bb6-5233-11e7-93da-726d0295c3dc.png)

But when using an older version of your repository and rolling back Xamarin.Forms to version 2.3.2.127 and run the app in UWP you can see that it does show up: 

![image](https://user-images.githubusercontent.com/1529389/27213138-dd1a5306-5232-11e7-8d30-a973ab9703c4.png)

I tried debugging for a very long time but it seems I cannot figure out how to show the menu once it is collapsed.

**Comment by slombardo** [comment]
Why was this closed?

**Comment by jamesmontemagno** [comment]
Because I fixed it, you can see the git commit

**Comment by slombardo** [comment]
This https://github.com/jamesmontemagno/Hanselman.Forms/commit/0b2a89855de2b4a09608025aa306dbfb9fc183f8#diff-1d08226d4b29e40045d3a1b8a9243be5R16 ??

Oh that's embarrassing.  Thanks!
