### ISSUE TITLE
Error retrieving parent for item: No resource found

### ISSUE THREAD

**Issue by kalkotekedar** [jamesmontemagno/Hanselman.Forms#47]
I am new to xamarin development am trying to build your project but getting this error

Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.	Hanselman.Android

I have tried to solve this  with but I am not getting any solution

**Comment by slombardo** [comment]
I am also getting this issue.

**Comment by jamesmontemagno** [comment]
Most likely need to compile against 7.0
