### ISSUE TITLE
VS2017 Support?

### ISSUE THREAD

**Issue by krugertech** [jamesmontemagno/Hanselman.Forms#50]
Compiling fails with visual studio community edition (fresh install) with tons of errors for:
1. Android
2. UWP

16 Errors: Example -->
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	Hanselman	C:\Xamarin\Hanselman.Forms-master\Hanselman.Forms-master\Hanselman.Portable\Views\PodcastPlaybackPage.xaml.cs	15	Active

**Comment by jamesmontemagno** [comment]
Fixed Up
