### ISSUE TITLE
isBusy/IsNotBusy?

### ISSUE THREAD

**Issue by kkrzysiek** [jamesmontemagno/Hanselman.Forms#53]
Hello :) 

it's not an issue just maybe a suggestion. 

In BaseViewModel you have "isBusy" and "isNotBusy".... 
wouldn't just one be enough? 

cheers! :)

**Comment by jamesmontemagno** [comment]
It is a nice thing to have so you don't need an inverse converter. Sometimes you want to only show things when not busy :)

**Comment by kkrzysiek** [comment]
yes I understand but why not to use one field? for example: bool isBusy

if(isBusy)
{
// do stuff when busy
}
else
{
// do stuff when not busy
}

that is simpler, right??

**Comment by jamesmontemagno** [comment]
Well, that is what I do, but in XAML if you are showing an element when something is not  busy.

Here is an example:
https://github.com/jamesmontemagno/app-coffeecups/blob/2985698505fe35e874fd86ca1da746ce48fbf665/CoffeeCups.Shared/View/CoffeesPage.xaml#L33

If I didn't have this then you would need a value converter.
