### ISSUE TITLE
The name 'DataTransfer' does not exist in the current context

### ISSUE THREAD

**Issue by scottspiller** [jamesmontemagno/Hanselman.Forms#63]
I'm getting an error compiling in the BlogDetailsView.cs with the latest code.  "The name 'DataTransfer' does not exist in the current context" on line 32.  Is DataTransfer in Xamarin Essentials?

My Xamarin Essentials is from Nuget version 1.0.1

**Comment by jamesmontemagno** [comment]
It has been changed to "Share". I will update the repo today :)
