### ISSUE TITLE
Fix Date to say 'Today', 'Yesterday'

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/Hanselman.Forms#74]

**Comment by Depechie** [comment]
Do you want this on Twitter and Blog list?

**Comment by jamesmontemagno** [comment]
probably both? :)

**Comment by Depechie** [comment]
Only see this now, but the current code does not guarantee that the field itself is a DateTime type.
So Humanizer can't be used in the `else` part... but that will not be a real problem I guess.

```
set
{
    if (DateTime.TryParse(value, out var time))
        publishDate = time.ToLocalTime().ToString("D");
    else
        publishDate = value;
}
```
