### ISSUE TITLE
Ask @shanselman what links to put in the app

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/Hanselman.Forms#85]
Currently on home page we have twitter/instatgram/facebook

**Comment by shanselman** [comment]
Link or links?

**Comment by shanselman** [comment]
plural

**Comment by jamesmontemagno** [comment]
Links! This is what the home page looks like right now:
![image](https://user-images.githubusercontent.com/1676321/53278018-b5e55280-36bb-11e9-92b9-f52a69f7093f.png)

Also going to update the About text with some links.

**Comment by shanselman** [comment]
Podcast first! Then twitter/IG/facebook. Not my finsta. ;)
